### ISSUE TITLE
Parameterized hex grid type

### ISSUE THREAD

**Issue by seagreen** [Voronchuk/hexagons#2]
I'm considering switching from `elm-hex-grid` to this library. Does this lib have an equivalent to the `HexGrid` type (defined [here](https://github.com/danneu/elm-hex-grid/blob/master/src/HexGrid.elm#L14)? I'm writing an arcade game and being able to build it around a `HexGrid TileState` is proving pretty handy.

**Comment by Voronchuk** [comment]
This library is using `Map` type as [storage engine](https://github.com/Voronchuk/hexagons/blob/master/Hexagons/Map.elm#L35).

Each cell stored in a dictionary with a unique 3 dimensional UID.

**Comment by Voronchuk** [comment]
Personally I'm using `Map` to define the layout, and store the actual objects by UID

```
type alias State =
    { ws_host : String
    , token : String
    , gameId : Int
    , dimension : ( Int, Int )
    , layout : Layout
    , cells : Map
    , highlightedCells : List Hash
    , hoveredCell : Hash
    , characters : Dict Int Character.State
    , controlled : List Int
    , initiative : List Int
    , activeCharId : Int
    , defaultLocation : Hash
    , movementRangeCells : List Hash
    , mapObjects : Dict Hash (List Object.State)
    , textures : Dict Hash Object.State
    , texturePatterns : List Object.TexturePattern
    }
```

Check `movementRangeCells`, `textures`, `highlightedCells`, `hoveredCell`, `mapObjects` fields

**Comment by seagreen** [comment]
Hey, thanks for the quick answer. I'm sorry it took me so long to get back to you.

And that setup totally makes sense. I like the idea of keeping the layout and the enumeration of units separate. That definitely takes care of my question, feel free to close this.
